# Generated by Django 6.0.5 on 2026-08-24 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_patient', models.BooleanField(default=True, help_text='Is this person receiving care?')),
                ('is_caregiver', models.BooleanField(default=False, help_text='Is this person providing care to others?')),
                ('is_client', models.BooleanField(default=True, help_text='Is this person a client of the service?')),
                ('can_self_report', models.BooleanField(default=True, help_text='Can this person enter their own vitals?')),
                ('known_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('care_type', models.CharField(choices=[('in_patient', 'In-patient Care'), ('outpatient', 'Outpatient Clinic'), ('home_care', 'Home Care'), ('self_care', 'Self Care')], default='home_care', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_caregiver', models.ForeignKey(blank=True, help_text='The caregiver assigned to this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_patients', to='monitoring.caregiver')),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='The doctor assigned to this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='monitoring.doctor')),
                ('patients_caring_for', models.ManyToManyField(blank=True, help_text='If this person is a caregiver, who do they care for?', related_name='caregivers', to='monitoring.patient')),
                ('user', models.OneToOneField(blank=True, help_text='User account for this client (for login access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('patient_self', 'Patient Self-Reported'), ('caregiver', 'Caregiver Entered'), ('doctor', 'Doctor Entered'), ('auto', 'Automated Device')], default='patient_self', help_text='How was this reading collected?', max_length=20)),
                ('fasting_blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('random_blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('systolic_bp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('pulse_rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 percentage', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('urine_glucose', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True)),
                ('urine_protein', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True)),
                ('urine_acetone', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True)),
                ('urine_bilirubin', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True)),
                ('urine_urobilinogen', models.CharField(blank=True, choices=[('weakly_positive', 'Weakly Positive'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=30, null=True)),
                ('urine_nitrite', models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive')], default=None, help_text='Leave empty if not tested', max_length=20, null=True)),
                ('entered_by', models.ForeignKey(blank=True, help_text='Who entered this reading (patient or caregiver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_readings', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='unreviewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.patient')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.vitalreading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary Care Physician'), ('specialist', 'Specialist'), ('consultant', 'Consultant'), ('temporary', 'Temporary/Stand-in')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(help_text='The doctor providing care', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='monitoring.doctor')),
                ('patient', models.ForeignKey(help_text='The patient receiving care', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('doctor', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='CaregiverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary Caregiver'), ('secondary', 'Secondary Caregiver'), ('professional', 'Professional Caregiver'), ('family', 'Family Caregiver'), ('self', 'Self Care')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('caregiver', models.ForeignKey(help_text='The person providing care', on_delete=django.db.models.deletion.CASCADE, related_name='caregiving_assignments', to='monitoring.patient')),
                ('patient', models.ForeignKey(help_text='The person receiving care', on_delete=django.db.models.deletion.CASCADE, related_name='received_care_assignments', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('caregiver', 'patient')},
            },
        ),
    ]
