# Generated by Django 6.0.5 on 2026-08-30 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('assessed', 'Patient Assessed'), ('monitored', 'Vitals Monitored'), ('medication', 'Medication Adjusted'), ('referred', 'Referred to Specialist'), ('contacted', 'Patient Contacted'), ('lab_test', 'Lab Test Ordered'), ('imaging', 'Imaging Ordered'), ('follow_up', 'Follow-up Scheduled'), ('escalated', 'Escalated to Emergency'), ('resolved', 'Resolved/Closed'), ('other', 'Other Action')], max_length=50)),
                ('description', models.TextField(help_text='Describe the action taken')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('clinical_findings', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='monitoring.alert')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
