# Generated by Django 6.0.5 on 2026-05-17 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_patient_vitalreading_alert_delete_vitalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, help_text='SpO2 percentage', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
