# Generated by Django 6.0.5 on 2026-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_vitalreading_oxygen_saturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='urine_acetone',
            field=models.CharField(choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default='negative', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='urine_bilirubin',
            field=models.CharField(choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default='negative', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='urine_glucose',
            field=models.CharField(choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default='negative', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='urine_nitrite',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive')], default='negative', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='urine_protein',
            field=models.CharField(choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default='negative', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='urine_urobilinogen',
            field=models.CharField(choices=[('weakly_positive', 'Weakly Positive'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default='weakly_positive', max_length=30),
        ),
    ]
