# Generated by Django 6.0.5 on 2026-07-07 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_vitalreading_urine_acetone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vitalreading',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='can_self_report',
            field=models.BooleanField(default=True, help_text='Can this person enter their own vitals?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_caregiver',
            field=models.BooleanField(default=False, help_text='Is this person providing care to others?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Is this person a client of the service?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_patient',
            field=models.BooleanField(default=True, help_text='Is this person receiving care?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patients_caring_for',
            field=models.ManyToManyField(blank=True, help_text='If this person is a caregiver, who do they care for?', related_name='caregivers', to='monitoring.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for this client (for login access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Who entered this reading (patient or caregiver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='source',
            field=models.CharField(choices=[('patient_self', 'Patient Self-Reported'), ('caregiver', 'Caregiver Entered'), ('doctor', 'Doctor Entered'), ('auto', 'Automated Device')], default='patient_self', help_text='How was this reading collected?', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_caregiver',
            field=models.ForeignKey(blank=True, help_text='The person who provides care for this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_type',
            field=models.CharField(choices=[('in_patient', 'In-patient Care'), ('outpatient', 'Outpatient Clinic'), ('home_care', 'Home Care'), ('self_care', 'Self Care')], default='home_care', max_length=20),
        ),
        migrations.CreateModel(
            name='CaregiverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary Caregiver'), ('secondary', 'Secondary Caregiver'), ('professional', 'Professional Caregiver'), ('family', 'Family Caregiver'), ('self', 'Self Care')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('caregiver', models.ForeignKey(help_text='The person providing care', on_delete=django.db.models.deletion.CASCADE, related_name='caregiving_assignments', to='monitoring.patient')),
                ('patient', models.ForeignKey(help_text='The person receiving care', on_delete=django.db.models.deletion.CASCADE, related_name='received_care_assignments', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('caregiver', 'patient')},
            },
        ),
    ]
