# Generated by Django 6.0.5 on 2026-07-12 21:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitoring', '0005_alter_alert_options_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
            ],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary Care Physician'), ('specialist', 'Specialist'), ('consultant', 'Consultant'), ('temporary', 'Temporary/Stand-in')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(help_text='The doctor providing care', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient receiving care', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
