# Generated by Django 6.0.5 on 2026-07-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_caregiver_doctor_doctorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_acetone',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_bilirubin',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_glucose',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_nitrite',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive')], default=None, help_text='Leave empty if not tested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_protein',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='urine_urobilinogen',
            field=models.CharField(blank=True, choices=[('weakly_positive', 'Weakly Positive'), ('plus', '+'), ('plus_2', '++'), ('plus_3', '+++'), ('plus_4', '++++')], default=None, help_text='Leave empty if not tested', max_length=30, null=True),
        ),
    ]
