# Generated by Django 6.0.5 on 2026-07-23 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_vitalreading_urine_acetone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caregiver',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_caregiver',
            field=models.ForeignKey(blank=True, help_text='The caregiver assigned to this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_patients', to='monitoring.caregiver'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='doctorassignment',
            name='doctor',
            field=models.ForeignKey(help_text='The doctor providing care', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='monitoring.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='The doctor assigned to this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='monitoring.doctor'),
        ),
    ]
